export const FETCH_BUDGET_START = 'FETCH_BUDGET_START';

export const FETCH_INCOME_SUCCESS = 'FETCH_INCOME_SUCCESS';
export const FETCH_INCOME_FAIL = 'FETCH_INCOME_FAIL';

export const FETCH_EXPENSE_SUCCESS = 'FETCH_EXPENSE_SUCCESS';
export const FETCH_EXPENSE_FAIL = 'FETCH_EXPENSE_FAIL';
