export const INIT_LOADING = 'INIT_LOADING';
export const INIT_LOADING_INCOME = 'INIT_LOADING_INCOME';
export const INIT_LOADING_EXPENSE = 'INIT_LOADING_EXPENSE';

export const FETCH_INCOME_SUCCESS = 'FETCH_INCOME_SUCCESS';
export const FETCH_INCOME_FAIL = 'FETCH_INCOME_FAIL';

export const FETCH_EXPENSE_SUCCESS = 'FETCH_EXPENSE_SUCCESS';
export const FETCH_EXPENSE_FAIL = 'FETCH_EXPENSE_FAIL';

export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';

export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAIL = 'DELETE_ITEM_FAIL';
